//
// SPDX-FileCopyrightText:  Copyright Hewlett Packard Enterprise Development LP

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.0
// source: internal/services/access-manager/accessmanager.proto

package accessmanager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessManager_Bootstrap_FullMethodName              = "/accessmanager.AccessManager/Bootstrap"
	AccessManager_GetPrincipalCredential_FullMethodName = "/accessmanager.AccessManager/GetPrincipalCredential"
	AccessManager_CreateObject_FullMethodName           = "/accessmanager.AccessManager/CreateObject"
	AccessManager_CreateDirectory_FullMethodName        = "/accessmanager.AccessManager/CreateDirectory"
	AccessManager_DeleteObject_FullMethodName           = "/accessmanager.AccessManager/DeleteObject"
	AccessManager_Annotate_FullMethodName               = "/accessmanager.AccessManager/Annotate"
	AccessManager_DeleteAnnotation_FullMethodName       = "/accessmanager.AccessManager/DeleteAnnotation"
	AccessManager_GetDetails_FullMethodName             = "/accessmanager.AccessManager/GetDetails"
	AccessManager_GetDatasetCredential_FullMethodName   = "/accessmanager.AccessManager/GetDatasetCredential"
	AccessManager_ValidateCredential_FullMethodName     = "/accessmanager.AccessManager/ValidateCredential"
	AccessManager_GetSigningKeys_FullMethodName         = "/accessmanager.AccessManager/GetSigningKeys"
)

// AccessManagerClient is the client API for AccessManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessManagerClient interface {
	Bootstrap(ctx context.Context, in *BoostrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error)
	// Used by an identity plugin to generate a signed credential for a user or workload. The plugin
	// must have the right to VouchFor the user or workload
	GetPrincipalCredential(ctx context.Context, in *GetPrincipalCredentialRequest, opts ...grpc.CallOption) (*GetPrincipalCredentialResponse, error)
	// Creates an object with the specified name. This object can be data, user, workload, role
	// or key. Subsequent calls can decorate the object with any required annotations like applied
	// roles, permissions or special keys. This object will be marked as a leaf, not a directory.
	CreateObject(ctx context.Context, in *CreateObjectRequest, opts ...grpc.CallOption) (*CreateObjectResponse, error)
	// Creates a directory with the specified name.
	CreateDirectory(ctx context.Context, in *CreateDirectoryRequest, opts ...grpc.CallOption) (*CreateDirectoryResponse, error)
	// Deletes any object at a specified path. This entails the deletion
	// of all of the metadata at that path as well and thus is likely
	// to require quite a number of permissions (UseRole+View on any role in
	// ACEs, Admin+View on the object). Internally, this function dispatches
	// to the specialized delete operation for whatever kind of object is
	// being deleted.
	// If the path is not an object, but is rather a directory, this operation
	// will only proceed if that directory has no children unless the recursive
	// flag is set in the request.
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error)
	// add or update an annotation on an object. If the unique value on the annotation
	// matches an existing annotation, that annotation is replaced. If the unique value
	// is novel, the annotation is added.
	Annotate(ctx context.Context, in *AnnotateRequest, opts ...grpc.CallOption) (*AnnotateResponse, error)
	DeleteAnnotation(ctx context.Context, in *DeleteAnnotationRequest, opts ...grpc.CallOption) (*DeleteAnnotationResponse, error)
	// Details for a particular path are returned with all roles,
	// direct or inherited and all permissions, also direct or
	// inherited.  Note that roles in the details may be redacted if the
	// caller does not have sufficient permission to see them. An error
	// will be returned if the path does not exist or if the caller
	// does not have view permission for the requested path.
	GetDetails(ctx context.Context, in *GetDetailsRequest, opts ...grpc.CallOption) (*GetDetailsResponse, error)
	GetDatasetCredential(ctx context.Context, in *GetDatasetCredentialRequest, opts ...grpc.CallOption) (*GetDatasetCredentialResponse, error)
	// credential validation
	ValidateCredential(ctx context.Context, in *ValidateCredentialRequest, opts ...grpc.CallOption) (*ValidateCredentialResponse, error)
	// get the list of all live signing keys
	GetSigningKeys(ctx context.Context, in *GetSigningKeysRequest, opts ...grpc.CallOption) (*GetSigningKeysResponse, error)
}

type accessManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessManagerClient(cc grpc.ClientConnInterface) AccessManagerClient {
	return &accessManagerClient{cc}
}

func (c *accessManagerClient) Bootstrap(ctx context.Context, in *BoostrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapResponse)
	err := c.cc.Invoke(ctx, AccessManager_Bootstrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) GetPrincipalCredential(ctx context.Context, in *GetPrincipalCredentialRequest, opts ...grpc.CallOption) (*GetPrincipalCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrincipalCredentialResponse)
	err := c.cc.Invoke(ctx, AccessManager_GetPrincipalCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) CreateObject(ctx context.Context, in *CreateObjectRequest, opts ...grpc.CallOption) (*CreateObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateObjectResponse)
	err := c.cc.Invoke(ctx, AccessManager_CreateObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) CreateDirectory(ctx context.Context, in *CreateDirectoryRequest, opts ...grpc.CallOption) (*CreateDirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDirectoryResponse)
	err := c.cc.Invoke(ctx, AccessManager_CreateDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectResponse)
	err := c.cc.Invoke(ctx, AccessManager_DeleteObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) Annotate(ctx context.Context, in *AnnotateRequest, opts ...grpc.CallOption) (*AnnotateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnotateResponse)
	err := c.cc.Invoke(ctx, AccessManager_Annotate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) DeleteAnnotation(ctx context.Context, in *DeleteAnnotationRequest, opts ...grpc.CallOption) (*DeleteAnnotationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAnnotationResponse)
	err := c.cc.Invoke(ctx, AccessManager_DeleteAnnotation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) GetDetails(ctx context.Context, in *GetDetailsRequest, opts ...grpc.CallOption) (*GetDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDetailsResponse)
	err := c.cc.Invoke(ctx, AccessManager_GetDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) GetDatasetCredential(ctx context.Context, in *GetDatasetCredentialRequest, opts ...grpc.CallOption) (*GetDatasetCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDatasetCredentialResponse)
	err := c.cc.Invoke(ctx, AccessManager_GetDatasetCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) ValidateCredential(ctx context.Context, in *ValidateCredentialRequest, opts ...grpc.CallOption) (*ValidateCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCredentialResponse)
	err := c.cc.Invoke(ctx, AccessManager_ValidateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessManagerClient) GetSigningKeys(ctx context.Context, in *GetSigningKeysRequest, opts ...grpc.CallOption) (*GetSigningKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSigningKeysResponse)
	err := c.cc.Invoke(ctx, AccessManager_GetSigningKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessManagerServer is the server API for AccessManager service.
// All implementations must embed UnimplementedAccessManagerServer
// for forward compatibility.
type AccessManagerServer interface {
	Bootstrap(context.Context, *BoostrapRequest) (*BootstrapResponse, error)
	// Used by an identity plugin to generate a signed credential for a user or workload. The plugin
	// must have the right to VouchFor the user or workload
	GetPrincipalCredential(context.Context, *GetPrincipalCredentialRequest) (*GetPrincipalCredentialResponse, error)
	// Creates an object with the specified name. This object can be data, user, workload, role
	// or key. Subsequent calls can decorate the object with any required annotations like applied
	// roles, permissions or special keys. This object will be marked as a leaf, not a directory.
	CreateObject(context.Context, *CreateObjectRequest) (*CreateObjectResponse, error)
	// Creates a directory with the specified name.
	CreateDirectory(context.Context, *CreateDirectoryRequest) (*CreateDirectoryResponse, error)
	// Deletes any object at a specified path. This entails the deletion
	// of all of the metadata at that path as well and thus is likely
	// to require quite a number of permissions (UseRole+View on any role in
	// ACEs, Admin+View on the object). Internally, this function dispatches
	// to the specialized delete operation for whatever kind of object is
	// being deleted.
	// If the path is not an object, but is rather a directory, this operation
	// will only proceed if that directory has no children unless the recursive
	// flag is set in the request.
	DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error)
	// add or update an annotation on an object. If the unique value on the annotation
	// matches an existing annotation, that annotation is replaced. If the unique value
	// is novel, the annotation is added.
	Annotate(context.Context, *AnnotateRequest) (*AnnotateResponse, error)
	DeleteAnnotation(context.Context, *DeleteAnnotationRequest) (*DeleteAnnotationResponse, error)
	// Details for a particular path are returned with all roles,
	// direct or inherited and all permissions, also direct or
	// inherited.  Note that roles in the details may be redacted if the
	// caller does not have sufficient permission to see them. An error
	// will be returned if the path does not exist or if the caller
	// does not have view permission for the requested path.
	GetDetails(context.Context, *GetDetailsRequest) (*GetDetailsResponse, error)
	GetDatasetCredential(context.Context, *GetDatasetCredentialRequest) (*GetDatasetCredentialResponse, error)
	// credential validation
	ValidateCredential(context.Context, *ValidateCredentialRequest) (*ValidateCredentialResponse, error)
	// get the list of all live signing keys
	GetSigningKeys(context.Context, *GetSigningKeysRequest) (*GetSigningKeysResponse, error)
	mustEmbedUnimplementedAccessManagerServer()
}

// UnimplementedAccessManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessManagerServer struct{}

func (UnimplementedAccessManagerServer) Bootstrap(context.Context, *BoostrapRequest) (*BootstrapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bootstrap not implemented")
}
func (UnimplementedAccessManagerServer) GetPrincipalCredential(context.Context, *GetPrincipalCredentialRequest) (*GetPrincipalCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrincipalCredential not implemented")
}
func (UnimplementedAccessManagerServer) CreateObject(context.Context, *CreateObjectRequest) (*CreateObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateObject not implemented")
}
func (UnimplementedAccessManagerServer) CreateDirectory(context.Context, *CreateDirectoryRequest) (*CreateDirectoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDirectory not implemented")
}
func (UnimplementedAccessManagerServer) DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteObject not implemented")
}
func (UnimplementedAccessManagerServer) Annotate(context.Context, *AnnotateRequest) (*AnnotateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Annotate not implemented")
}
func (UnimplementedAccessManagerServer) DeleteAnnotation(context.Context, *DeleteAnnotationRequest) (*DeleteAnnotationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAnnotation not implemented")
}
func (UnimplementedAccessManagerServer) GetDetails(context.Context, *GetDetailsRequest) (*GetDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetails not implemented")
}
func (UnimplementedAccessManagerServer) GetDatasetCredential(context.Context, *GetDatasetCredentialRequest) (*GetDatasetCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDatasetCredential not implemented")
}
func (UnimplementedAccessManagerServer) ValidateCredential(context.Context, *ValidateCredentialRequest) (*ValidateCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateCredential not implemented")
}
func (UnimplementedAccessManagerServer) GetSigningKeys(context.Context, *GetSigningKeysRequest) (*GetSigningKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSigningKeys not implemented")
}
func (UnimplementedAccessManagerServer) mustEmbedUnimplementedAccessManagerServer() {}
func (UnimplementedAccessManagerServer) testEmbeddedByValue()                       {}

// UnsafeAccessManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessManagerServer will
// result in compilation errors.
type UnsafeAccessManagerServer interface {
	mustEmbedUnimplementedAccessManagerServer()
}

func RegisterAccessManagerServer(s grpc.ServiceRegistrar, srv AccessManagerServer) {
	// If the following call panics, it indicates UnimplementedAccessManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessManager_ServiceDesc, srv)
}

func _AccessManager_Bootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoostrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).Bootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessManager_Bootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).Bootstrap(ctx, req.(*BoostrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_GetPrincipalCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrincipalCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).GetPrincipalCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessManager_GetPrincipalCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).GetPrincipalCredential(ctx, req.(*GetPrincipalCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_CreateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).CreateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessManager_CreateObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).CreateObject(ctx, req.(*CreateObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_CreateDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).CreateDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessManager_CreateDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).CreateDirectory(ctx, req.(*CreateDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessManager_DeleteObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_Annotate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnotateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).Annotate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessManager_Annotate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).Annotate(ctx, req.(*AnnotateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_DeleteAnnotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAnnotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).DeleteAnnotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessManager_DeleteAnnotation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).DeleteAnnotation(ctx, req.(*DeleteAnnotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_GetDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).GetDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessManager_GetDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).GetDetails(ctx, req.(*GetDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_GetDatasetCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatasetCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).GetDatasetCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessManager_GetDatasetCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).GetDatasetCredential(ctx, req.(*GetDatasetCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_ValidateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).ValidateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessManager_ValidateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).ValidateCredential(ctx, req.(*ValidateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessManager_GetSigningKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSigningKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessManagerServer).GetSigningKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessManager_GetSigningKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessManagerServer).GetSigningKeys(ctx, req.(*GetSigningKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessManager_ServiceDesc is the grpc.ServiceDesc for AccessManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accessmanager.AccessManager",
	HandlerType: (*AccessManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bootstrap",
			Handler:    _AccessManager_Bootstrap_Handler,
		},
		{
			MethodName: "GetPrincipalCredential",
			Handler:    _AccessManager_GetPrincipalCredential_Handler,
		},
		{
			MethodName: "CreateObject",
			Handler:    _AccessManager_CreateObject_Handler,
		},
		{
			MethodName: "CreateDirectory",
			Handler:    _AccessManager_CreateDirectory_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _AccessManager_DeleteObject_Handler,
		},
		{
			MethodName: "Annotate",
			Handler:    _AccessManager_Annotate_Handler,
		},
		{
			MethodName: "DeleteAnnotation",
			Handler:    _AccessManager_DeleteAnnotation_Handler,
		},
		{
			MethodName: "GetDetails",
			Handler:    _AccessManager_GetDetails_Handler,
		},
		{
			MethodName: "GetDatasetCredential",
			Handler:    _AccessManager_GetDatasetCredential_Handler,
		},
		{
			MethodName: "ValidateCredential",
			Handler:    _AccessManager_ValidateCredential_Handler,
		},
		{
			MethodName: "GetSigningKeys",
			Handler:    _AccessManager_GetSigningKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/services/access-manager/accessmanager.proto",
}
