//
// SPDX-FileCopyrightText:  Copyright Hewlett Packard Enterprise Development LP

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.0
// source: internal/services/access-manager/credentials.proto

package accessmanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DelegatedAttributes []string               `protobuf:"bytes,1,rep,name=delegatedAttributes,proto3" json:"delegatedAttributes,omitempty"` // if non-empty, these are the attributes to pass through (delegate)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DataInfo) Reset() {
	*x = DataInfo{}
	mi := &file_internal_services_access_manager_credentials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInfo) ProtoMessage() {}

func (x *DataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_services_access_manager_credentials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInfo.ProtoReflect.Descriptor instead.
func (*DataInfo) Descriptor() ([]byte, []int) {
	return file_internal_services_access_manager_credentials_proto_rawDescGZIP(), []int{0}
}

func (x *DataInfo) GetDelegatedAttributes() []string {
	if x != nil {
		return x.DelegatedAttributes
	}
	return nil
}

type DataCredentialProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Factory       string                 `protobuf:"bytes,1,opt,name=factory,proto3" json:"factory,omitempty"` // URL of credential factory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCredentialProvider) Reset() {
	*x = DataCredentialProvider{}
	mi := &file_internal_services_access_manager_credentials_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCredentialProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCredentialProvider) ProtoMessage() {}

func (x *DataCredentialProvider) ProtoReflect() protoreflect.Message {
	mi := &file_internal_services_access_manager_credentials_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCredentialProvider.ProtoReflect.Descriptor instead.
func (*DataCredentialProvider) Descriptor() ([]byte, []int) {
	return file_internal_services_access_manager_credentials_proto_rawDescGZIP(), []int{1}
}

func (x *DataCredentialProvider) GetFactory() string {
	if x != nil {
		return x.Factory
	}
	return ""
}

var File_internal_services_access_manager_credentials_proto protoreflect.FileDescriptor

var file_internal_services_access_manager_credentials_proto_rawDesc = string([]byte{
	0x0a, 0x32, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x22, 0x3c, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x30, 0x0a, 0x13, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x64, 0x65,
	0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x22, 0x32, 0x0a, 0x16, 0x44, 0x61, 0x74, 0x61, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x66,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x21, 0x5a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_internal_services_access_manager_credentials_proto_rawDescOnce sync.Once
	file_internal_services_access_manager_credentials_proto_rawDescData []byte
)

func file_internal_services_access_manager_credentials_proto_rawDescGZIP() []byte {
	file_internal_services_access_manager_credentials_proto_rawDescOnce.Do(func() {
		file_internal_services_access_manager_credentials_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_services_access_manager_credentials_proto_rawDesc), len(file_internal_services_access_manager_credentials_proto_rawDesc)))
	})
	return file_internal_services_access_manager_credentials_proto_rawDescData
}

var file_internal_services_access_manager_credentials_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_services_access_manager_credentials_proto_goTypes = []any{
	(*DataInfo)(nil),               // 0: accessmanager.DataInfo
	(*DataCredentialProvider)(nil), // 1: accessmanager.DataCredentialProvider
}
var file_internal_services_access_manager_credentials_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_services_access_manager_credentials_proto_init() }
func file_internal_services_access_manager_credentials_proto_init() {
	if File_internal_services_access_manager_credentials_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_services_access_manager_credentials_proto_rawDesc), len(file_internal_services_access_manager_credentials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_services_access_manager_credentials_proto_goTypes,
		DependencyIndexes: file_internal_services_access_manager_credentials_proto_depIdxs,
		MessageInfos:      file_internal_services_access_manager_credentials_proto_msgTypes,
	}.Build()
	File_internal_services_access_manager_credentials_proto = out.File
	file_internal_services_access_manager_credentials_proto_goTypes = nil
	file_internal_services_access_manager_credentials_proto_depIdxs = nil
}
