// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: auditmanager.proto

package hdp_proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuditQueryManagerClient is the client API for AuditQueryManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditQueryManagerClient interface {
	GetHistoricalPermissions(ctx context.Context, in *HistoricalPermissionsRequest, opts ...grpc.CallOption) (*HistoricalPermissionsResponse, error)
	AddAccessLog(ctx context.Context, in *AccessLogRequest, opts ...grpc.CallOption) (*AccessLogResponse, error)
	GetAccessLogs(ctx context.Context, in *HistoricalPermissionsInfo, opts ...grpc.CallOption) (*HistoricalPermissionsResponse, error)
}

type auditQueryManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditQueryManagerClient(cc grpc.ClientConnInterface) AuditQueryManagerClient {
	return &auditQueryManagerClient{cc}
}

func (c *auditQueryManagerClient) GetHistoricalPermissions(ctx context.Context, in *HistoricalPermissionsRequest, opts ...grpc.CallOption) (*HistoricalPermissionsResponse, error) {
	out := new(HistoricalPermissionsResponse)
	err := c.cc.Invoke(ctx, "/accessmanager.AuditQueryManager/GetHistoricalPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditQueryManagerClient) AddAccessLog(ctx context.Context, in *AccessLogRequest, opts ...grpc.CallOption) (*AccessLogResponse, error) {
	out := new(AccessLogResponse)
	err := c.cc.Invoke(ctx, "/accessmanager.AuditQueryManager/AddAccessLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditQueryManagerClient) GetAccessLogs(ctx context.Context, in *HistoricalPermissionsInfo, opts ...grpc.CallOption) (*HistoricalPermissionsResponse, error) {
	out := new(HistoricalPermissionsResponse)
	err := c.cc.Invoke(ctx, "/accessmanager.AuditQueryManager/GetAccessLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditQueryManagerServer is the server API for AuditQueryManager service.
// All implementations must embed UnimplementedAuditQueryManagerServer
// for forward compatibility
type AuditQueryManagerServer interface {
	GetHistoricalPermissions(context.Context, *HistoricalPermissionsRequest) (*HistoricalPermissionsResponse, error)
	AddAccessLog(context.Context, *AccessLogRequest) (*AccessLogResponse, error)
	GetAccessLogs(context.Context, *HistoricalPermissionsInfo) (*HistoricalPermissionsResponse, error)
	mustEmbedUnimplementedAuditQueryManagerServer()
}

// UnimplementedAuditQueryManagerServer must be embedded to have forward compatible implementations.
type UnimplementedAuditQueryManagerServer struct {
}

func (UnimplementedAuditQueryManagerServer) GetHistoricalPermissions(context.Context, *HistoricalPermissionsRequest) (*HistoricalPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistoricalPermissions not implemented")
}
func (UnimplementedAuditQueryManagerServer) AddAccessLog(context.Context, *AccessLogRequest) (*AccessLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAccessLog not implemented")
}
func (UnimplementedAuditQueryManagerServer) GetAccessLogs(context.Context, *HistoricalPermissionsInfo) (*HistoricalPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessLogs not implemented")
}
func (UnimplementedAuditQueryManagerServer) mustEmbedUnimplementedAuditQueryManagerServer() {}

// UnsafeAuditQueryManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditQueryManagerServer will
// result in compilation errors.
type UnsafeAuditQueryManagerServer interface {
	mustEmbedUnimplementedAuditQueryManagerServer()
}

func RegisterAuditQueryManagerServer(s grpc.ServiceRegistrar, srv AuditQueryManagerServer) {
	s.RegisterService(&AuditQueryManager_ServiceDesc, srv)
}

func _AuditQueryManager_GetHistoricalPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditQueryManagerServer).GetHistoricalPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accessmanager.AuditQueryManager/GetHistoricalPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditQueryManagerServer).GetHistoricalPermissions(ctx, req.(*HistoricalPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditQueryManager_AddAccessLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditQueryManagerServer).AddAccessLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accessmanager.AuditQueryManager/AddAccessLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditQueryManagerServer).AddAccessLog(ctx, req.(*AccessLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditQueryManager_GetAccessLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalPermissionsInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditQueryManagerServer).GetAccessLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accessmanager.AuditQueryManager/GetAccessLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditQueryManagerServer).GetAccessLogs(ctx, req.(*HistoricalPermissionsInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditQueryManager_ServiceDesc is the grpc.ServiceDesc for AuditQueryManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditQueryManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accessmanager.AuditQueryManager",
	HandlerType: (*AuditQueryManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHistoricalPermissions",
			Handler:    _AuditQueryManager_GetHistoricalPermissions_Handler,
		},
		{
			MethodName: "AddAccessLog",
			Handler:    _AuditQueryManager_AddAccessLog_Handler,
		},
		{
			MethodName: "GetAccessLogs",
			Handler:    _AuditQueryManager_GetAccessLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auditmanager.proto",
}
