// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: credentialmanager.proto

package hdp_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CredentialManager_GetTemporaryCredential_FullMethodName = "/accessmanager.CredentialManager/GetTemporaryCredential"
)

// CredentialManagerClient is the client API for CredentialManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CredentialManagerClient interface {
	GetTemporaryCredential(ctx context.Context, in *GetCredentialRequest, opts ...grpc.CallOption) (*GetCredentialResponse, error)
}

type credentialManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialManagerClient(cc grpc.ClientConnInterface) CredentialManagerClient {
	return &credentialManagerClient{cc}
}

func (c *credentialManagerClient) GetTemporaryCredential(ctx context.Context, in *GetCredentialRequest, opts ...grpc.CallOption) (*GetCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCredentialResponse)
	err := c.cc.Invoke(ctx, CredentialManager_GetTemporaryCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialManagerServer is the server API for CredentialManager service.
// All implementations must embed UnimplementedCredentialManagerServer
// for forward compatibility.
type CredentialManagerServer interface {
	GetTemporaryCredential(context.Context, *GetCredentialRequest) (*GetCredentialResponse, error)
	mustEmbedUnimplementedCredentialManagerServer()
}

// UnimplementedCredentialManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCredentialManagerServer struct{}

func (UnimplementedCredentialManagerServer) GetTemporaryCredential(context.Context, *GetCredentialRequest) (*GetCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemporaryCredential not implemented")
}
func (UnimplementedCredentialManagerServer) mustEmbedUnimplementedCredentialManagerServer() {}
func (UnimplementedCredentialManagerServer) testEmbeddedByValue()                           {}

// UnsafeCredentialManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialManagerServer will
// result in compilation errors.
type UnsafeCredentialManagerServer interface {
	mustEmbedUnimplementedCredentialManagerServer()
}

func RegisterCredentialManagerServer(s grpc.ServiceRegistrar, srv CredentialManagerServer) {
	// If the following call pancis, it indicates UnimplementedCredentialManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CredentialManager_ServiceDesc, srv)
}

func _CredentialManager_GetTemporaryCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialManagerServer).GetTemporaryCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialManager_GetTemporaryCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialManagerServer).GetTemporaryCredential(ctx, req.(*GetCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CredentialManager_ServiceDesc is the grpc.ServiceDesc for CredentialManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CredentialManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accessmanager.CredentialManager",
	HandlerType: (*CredentialManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTemporaryCredential",
			Handler:    _CredentialManager_GetTemporaryCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "credentialmanager.proto",
}
