// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: credentialmanager.proto

package hdp_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	WildCardUrl   string                 `protobuf:"bytes,2,opt,name=wildCardUrl,proto3" json:"wildCardUrl,omitempty"`
	Operations    []Operation            `protobuf:"varint,3,rep,packed,name=operations,proto3,enum=Operation" json:"operations,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	CallerId      string                 `protobuf:"bytes,5,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialRequest) Reset() {
	*x = GetCredentialRequest{}
	mi := &file_credentialmanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialRequest) ProtoMessage() {}

func (x *GetCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialmanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialRequest) Descriptor() ([]byte, []int) {
	return file_credentialmanager_proto_rawDescGZIP(), []int{0}
}

func (x *GetCredentialRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetCredentialRequest) GetWildCardUrl() string {
	if x != nil {
		return x.WildCardUrl
	}
	return ""
}

func (x *GetCredentialRequest) GetOperations() []Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *GetCredentialRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetCredentialRequest) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

type GetCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   map[string]string      `protobuf:"bytes,2,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         *Status                `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialResponse) Reset() {
	*x = GetCredentialResponse{}
	mi := &file_credentialmanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialResponse) ProtoMessage() {}

func (x *GetCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialmanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialResponse) Descriptor() ([]byte, []int) {
	return file_credentialmanager_proto_rawDescGZIP(), []int{1}
}

func (x *GetCredentialResponse) GetCredentials() map[string]string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *GetCredentialResponse) GetError() *Status {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_credentialmanager_proto protoreflect.FileDescriptor

const file_credentialmanager_proto_rawDesc = "" +
	"\n" +
	"\x17credentialmanager.proto\x12\raccessmanager\x1a\fcommon.proto\"\xa7\x01\n" +
	"\x14GetCredentialRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12 \n" +
	"\vwildCardUrl\x18\x02 \x01(\tR\vwildCardUrl\x12*\n" +
	"\n" +
	"operations\x18\x03 \x03(\x0e2\n" +
	".OperationR\n" +
	"operations\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1b\n" +
	"\tcaller_id\x18\x05 \x01(\tR\bcallerId\"\xcf\x01\n" +
	"\x15GetCredentialResponse\x12W\n" +
	"\vcredentials\x18\x02 \x03(\v25.accessmanager.GetCredentialResponse.CredentialsEntryR\vcredentials\x12\x1d\n" +
	"\x05error\x18\x03 \x01(\v2\a.StatusR\x05error\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012x\n" +
	"\x11CredentialManager\x12c\n" +
	"\x16GetTemporaryCredential\x12#.accessmanager.GetCredentialRequest\x1a$.accessmanager.GetCredentialResponseB\rZ\v./am-protob\x06proto3"

var (
	file_credentialmanager_proto_rawDescOnce sync.Once
	file_credentialmanager_proto_rawDescData []byte
)

func file_credentialmanager_proto_rawDescGZIP() []byte {
	file_credentialmanager_proto_rawDescOnce.Do(func() {
		file_credentialmanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credentialmanager_proto_rawDesc), len(file_credentialmanager_proto_rawDesc)))
	})
	return file_credentialmanager_proto_rawDescData
}

var file_credentialmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_credentialmanager_proto_goTypes = []any{
	(*GetCredentialRequest)(nil),  // 0: accessmanager.GetCredentialRequest
	(*GetCredentialResponse)(nil), // 1: accessmanager.GetCredentialResponse
	nil,                           // 2: accessmanager.GetCredentialResponse.CredentialsEntry
	(Operation)(0),                // 3: Operation
	(*Status)(nil),                // 4: Status
}
var file_credentialmanager_proto_depIdxs = []int32{
	3, // 0: accessmanager.GetCredentialRequest.operations:type_name -> Operation
	2, // 1: accessmanager.GetCredentialResponse.credentials:type_name -> accessmanager.GetCredentialResponse.CredentialsEntry
	4, // 2: accessmanager.GetCredentialResponse.error:type_name -> Status
	0, // 3: accessmanager.CredentialManager.GetTemporaryCredential:input_type -> accessmanager.GetCredentialRequest
	1, // 4: accessmanager.CredentialManager.GetTemporaryCredential:output_type -> accessmanager.GetCredentialResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_credentialmanager_proto_init() }
func file_credentialmanager_proto_init() {
	if File_credentialmanager_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credentialmanager_proto_rawDesc), len(file_credentialmanager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credentialmanager_proto_goTypes,
		DependencyIndexes: file_credentialmanager_proto_depIdxs,
		MessageInfos:      file_credentialmanager_proto_msgTypes,
	}.Build()
	File_credentialmanager_proto = out.File
	file_credentialmanager_proto_goTypes = nil
	file_credentialmanager_proto_depIdxs = nil
}
