//
// SPDX-FileCopyrightText:  Copyright Hewlett Packard Enterprise Development LP

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.0
// source: meta.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// the legal operations
type Operation int32

const (
	Operation_INVALID   Operation = 0 // place-holder for impossible situations
	Operation_READ      Operation = 1 // ead from a dataset
	Operation_WRITE     Operation = 2 // rite to a dataset, create children of a directory
	Operation_VIEW      Operation = 3 // s an entity visible (could be a dataset, role, user, directory...)
	Operation_ADMIN     Operation = 4 // an permissions on an entity be modified?
	Operation_USEROLE   Operation = 5 // an a role be used in an ACL?
	Operation_APPLYROLE Operation = 6 // an a role be added to a principal?
	Operation_VOUCHFOR  Operation = 7 // can a plugin vouch for an identity?
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "INVALID",
		1: "READ",
		2: "WRITE",
		3: "VIEW",
		4: "ADMIN",
		5: "USEROLE",
		6: "APPLYROLE",
		7: "VOUCHFOR",
	}
	Operation_value = map[string]int32{
		"INVALID":   0,
		"READ":      1,
		"WRITE":     2,
		"VIEW":      3,
		"ADMIN":     4,
		"USEROLE":   5,
		"APPLYROLE": 6,
		"VOUCHFOR":  7,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_meta_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_meta_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{0}
}

// this is the public view of the standard annotations
type ACE struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Op    Operation              `protobuf:"varint,1,opt,name=op,proto3,enum=metadata.Operation" json:"op,omitempty"`
	Local bool                   `protobuf:"varint,2,opt,name=local,proto3" json:"local,omitempty"` // if true, ACE is not inherited
	Agent bool                   `protobuf:"varint,9,opt,name=agent,proto3" json:"agent,omitempty"` // if true, this ACE is for the agent of the op else it is for the target
	Acls  []*ACL                 `protobuf:"bytes,3,rep,name=acls,proto3" json:"acls,omitempty"`    // all of these ACLs must be satisfied
	// common fields for all annotations
	Tag           string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`                  // "ace" for all kinds of ACEs
	Unique        int64  `protobuf:"varint,5,opt,name=unique,proto3" json:"unique,omitempty"`           // unique-ifier to avoid collisions for annotations on a metadata node
	Version       int64  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`         // version for safe updates
	StartMillis   int64  `protobuf:"varint,7,opt,name=startMillis,proto3" json:"startMillis,omitempty"` // what clock time does this ACE take effect
	EndMillis     int64  `protobuf:"varint,8,opt,name=endMillis,proto3" json:"endMillis,omitempty"`     // when does this ACE lose effect
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACE) Reset() {
	*x = ACE{}
	mi := &file_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACE) ProtoMessage() {}

func (x *ACE) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACE.ProtoReflect.Descriptor instead.
func (*ACE) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{0}
}

func (x *ACE) GetOp() Operation {
	if x != nil {
		return x.Op
	}
	return Operation_INVALID
}

func (x *ACE) GetLocal() bool {
	if x != nil {
		return x.Local
	}
	return false
}

func (x *ACE) GetAgent() bool {
	if x != nil {
		return x.Agent
	}
	return false
}

func (x *ACE) GetAcls() []*ACL {
	if x != nil {
		return x.Acls
	}
	return nil
}

func (x *ACE) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ACE) GetUnique() int64 {
	if x != nil {
		return x.Unique
	}
	return 0
}

func (x *ACE) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ACE) GetStartMillis() int64 {
	if x != nil {
		return x.StartMillis
	}
	return 0
}

func (x *ACE) GetEndMillis() int64 {
	if x != nil {
		return x.EndMillis
	}
	return 0
}

type ACL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []string               `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACL) Reset() {
	*x = ACL{}
	mi := &file_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACL) ProtoMessage() {}

func (x *ACL) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACL.ProtoReflect.Descriptor instead.
func (*ACL) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{1}
}

func (x *ACL) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type AppliedRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Unique        int64                  `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	StartMillis   int64                  `protobuf:"varint,5,opt,name=startMillis,proto3" json:"startMillis,omitempty"`
	EndMillis     int64                  `protobuf:"varint,6,opt,name=endMillis,proto3" json:"endMillis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppliedRole) Reset() {
	*x = AppliedRole{}
	mi := &file_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppliedRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppliedRole) ProtoMessage() {}

func (x *AppliedRole) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppliedRole.ProtoReflect.Descriptor instead.
func (*AppliedRole) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{2}
}

func (x *AppliedRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AppliedRole) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AppliedRole) GetUnique() int64 {
	if x != nil {
		return x.Unique
	}
	return 0
}

func (x *AppliedRole) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AppliedRole) GetStartMillis() int64 {
	if x != nil {
		return x.StartMillis
	}
	return 0
}

func (x *AppliedRole) GetEndMillis() int64 {
	if x != nil {
		return x.EndMillis
	}
	return 0
}

type UserAnnotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Unique        int64                  `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	StartMillis   int64                  `protobuf:"varint,5,opt,name=startMillis,proto3" json:"startMillis,omitempty"`
	EndMillis     int64                  `protobuf:"varint,6,opt,name=endMillis,proto3" json:"endMillis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAnnotation) Reset() {
	*x = UserAnnotation{}
	mi := &file_meta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAnnotation) ProtoMessage() {}

func (x *UserAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAnnotation.ProtoReflect.Descriptor instead.
func (*UserAnnotation) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{3}
}

func (x *UserAnnotation) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *UserAnnotation) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UserAnnotation) GetUnique() int64 {
	if x != nil {
		return x.Unique
	}
	return 0
}

func (x *UserAnnotation) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UserAnnotation) GetStartMillis() int64 {
	if x != nil {
		return x.StartMillis
	}
	return 0
}

func (x *UserAnnotation) GetEndMillis() int64 {
	if x != nil {
		return x.EndMillis
	}
	return 0
}

// And these are the forms that are used for persistence
// the difference is that things like the unique ID, version
// and duration are factored out for use by the storage system.
// Underneath, the annotation-type-specific fields are stored
// in their stripped form.
type AnnotationWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unique        int64                  `protobuf:"varint,1,opt,name=Unique,proto3" json:"Unique,omitempty"`           // unique-ifier to avoid collisions for annotations on a metadata node
	Version       int64                  `protobuf:"varint,2,opt,name=Version,proto3" json:"Version,omitempty"`         // version for safe updates
	Global        int64                  `protobuf:"varint,3,opt,name=Global,proto3" json:"Global,omitempty"`           // the global revision number for last modification
	StartMillis   int64                  `protobuf:"varint,4,opt,name=StartMillis,proto3" json:"StartMillis,omitempty"` // what clock time did this annotation take effect
	EndMillis     int64                  `protobuf:"varint,5,opt,name=EndMillis,proto3" json:"EndMillis,omitempty"`     // when does this annotation lose effect
	Tag           string                 `protobuf:"bytes,6,opt,name=Tag,proto3" json:"Tag,omitempty"`                  // hint for the interpretation of the value such as "role", "ace", or "ssh-key"
	Raw           *anypb.Any             `protobuf:"bytes,7,opt,name=Raw,proto3" json:"Raw,omitempty"`                  // any data specific to the annotation goes here in marshalled form
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotationWrapper) Reset() {
	*x = AnnotationWrapper{}
	mi := &file_meta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotationWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotationWrapper) ProtoMessage() {}

func (x *AnnotationWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotationWrapper.ProtoReflect.Descriptor instead.
func (*AnnotationWrapper) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{4}
}

func (x *AnnotationWrapper) GetUnique() int64 {
	if x != nil {
		return x.Unique
	}
	return 0
}

func (x *AnnotationWrapper) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AnnotationWrapper) GetGlobal() int64 {
	if x != nil {
		return x.Global
	}
	return 0
}

func (x *AnnotationWrapper) GetStartMillis() int64 {
	if x != nil {
		return x.StartMillis
	}
	return 0
}

func (x *AnnotationWrapper) GetEndMillis() int64 {
	if x != nil {
		return x.EndMillis
	}
	return 0
}

func (x *AnnotationWrapper) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AnnotationWrapper) GetRaw() *anypb.Any {
	if x != nil {
		return x.Raw
	}
	return nil
}

// stores permissions for a single operation
type ACEPersist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Operation              `protobuf:"varint,1,opt,name=op,proto3,enum=metadata.Operation" json:"op,omitempty"` // what operation is controlled
	Local         bool                   `protobuf:"varint,2,opt,name=local,proto3" json:"local,omitempty"`                   // if true, ACE is not inherited
	Acls          []*ACLPersist          `protobuf:"bytes,3,rep,name=acls,proto3" json:"acls,omitempty"`                      // all of these ACLs must be satisfied
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACEPersist) Reset() {
	*x = ACEPersist{}
	mi := &file_meta_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACEPersist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACEPersist) ProtoMessage() {}

func (x *ACEPersist) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACEPersist.ProtoReflect.Descriptor instead.
func (*ACEPersist) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{5}
}

func (x *ACEPersist) GetOp() Operation {
	if x != nil {
		return x.Op
	}
	return Operation_INVALID
}

func (x *ACEPersist) GetLocal() bool {
	if x != nil {
		return x.Local
	}
	return false
}

func (x *ACEPersist) GetAcls() []*ACLPersist {
	if x != nil {
		return x.Acls
	}
	return nil
}

// implements a conventional ACL. User or workload must have at least one of these attributes
type ACLPersist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []string               `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACLPersist) Reset() {
	*x = ACLPersist{}
	mi := &file_meta_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACLPersist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACLPersist) ProtoMessage() {}

func (x *ACLPersist) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACLPersist.ProtoReflect.Descriptor instead.
func (*ACLPersist) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{6}
}

func (x *ACLPersist) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// the side data for an applied role annotation
type RolePersist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePersist) Reset() {
	*x = RolePersist{}
	mi := &file_meta_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePersist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePersist) ProtoMessage() {}

func (x *RolePersist) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePersist.ProtoReflect.Descriptor instead.
func (*RolePersist) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{7}
}

func (x *RolePersist) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// how we store JSON data such as for dataset info
type JsonPersist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonPersist) Reset() {
	*x = JsonPersist{}
	mi := &file_meta_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonPersist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonPersist) ProtoMessage() {}

func (x *JsonPersist) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonPersist.ProtoReflect.Descriptor instead.
func (*JsonPersist) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{8}
}

func (x *JsonPersist) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type TaggedString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaggedString) Reset() {
	*x = TaggedString{}
	mi := &file_meta_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaggedString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaggedString) ProtoMessage() {}

func (x *TaggedString) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaggedString.ProtoReflect.Descriptor instead.
func (*TaggedString) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{9}
}

func (x *TaggedString) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TaggedString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type S3Urls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	UrlWildcard   string                 `protobuf:"bytes,3,opt,name=urlWildcard,proto3" json:"urlWildcard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3Urls) Reset() {
	*x = S3Urls{}
	mi := &file_meta_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Urls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Urls) ProtoMessage() {}

func (x *S3Urls) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Urls.ProtoReflect.Descriptor instead.
func (*S3Urls) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{10}
}

func (x *S3Urls) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *S3Urls) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *S3Urls) GetUrlWildcard() string {
	if x != nil {
		return x.UrlWildcard
	}
	return ""
}

// how we store credential signing keys
type SigningKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       int64                  `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"` // when was this key created
	Unique        int64                  `protobuf:"varint,2,opt,name=unique,proto3" json:"unique,omitempty"`   // bits that identify this key, no relation to the key itself
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`          // the key in PKCS1 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningKey) Reset() {
	*x = SigningKey{}
	mi := &file_meta_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningKey) ProtoMessage() {}

func (x *SigningKey) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningKey.ProtoReflect.Descriptor instead.
func (*SigningKey) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{11}
}

func (x *SigningKey) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *SigningKey) GetUnique() int64 {
	if x != nil {
		return x.Unique
	}
	return 0
}

func (x *SigningKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_meta_proto protoreflect.FileDescriptor

var file_meta_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xfd, 0x01, 0x0a, 0x03, 0x41, 0x43, 0x45, 0x12, 0x23, 0x0a, 0x02, 0x6f, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x61, 0x63,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x41, 0x43, 0x4c, 0x52, 0x04, 0x61, 0x63, 0x6c, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x69, 0x6c,
	0x6c, 0x69, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x4d, 0x69, 0x6c, 0x6c, 0x69,
	0x73, 0x22, 0x1b, 0x0a, 0x03, 0x41, 0x43, 0x4c, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0xa5,
	0x01, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x74, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4d,
	0x69, 0x6c, 0x6c, 0x69, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x4d,
	0x69, 0x6c, 0x6c, 0x69, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x6e, 0x64,
	0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x22, 0xa8, 0x01, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x69, 0x6c,
	0x6c, 0x69, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x4d, 0x69, 0x6c, 0x6c, 0x69,
	0x73, 0x22, 0xd7, 0x01, 0x0a, 0x11, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x69, 0x6c,
	0x6c, 0x69, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x6e, 0x64, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x45, 0x6e, 0x64, 0x4d, 0x69, 0x6c, 0x6c, 0x69,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x54, 0x61, 0x67, 0x12, 0x26, 0x0a, 0x03, 0x52, 0x61, 0x77, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x03, 0x52, 0x61, 0x77, 0x22, 0x73, 0x0a, 0x0b, 0x41,
	0x43, 0x45, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x02, 0x6f, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x6f, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x29, 0x0a, 0x04, 0x61, 0x63, 0x6c, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x41,
	0x43, 0x4c, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x52, 0x04, 0x61, 0x63, 0x6c, 0x73,
	0x22, 0x23, 0x0a, 0x0b, 0x41, 0x43, 0x4c, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x5f, 0x70, 0x65,
	0x72, 0x73, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x22, 0x0a, 0x0c, 0x4a, 0x73, 0x6f,
	0x6e, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x36, 0x0a,
	0x0c, 0x54, 0x61, 0x67, 0x67, 0x65, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4e, 0x0a, 0x06, 0x53, 0x33, 0x55, 0x72, 0x6c, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x72, 0x6c, 0x57, 0x69, 0x6c, 0x64, 0x63, 0x61,
	0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x72, 0x6c, 0x57, 0x69, 0x6c,
	0x64, 0x63, 0x61, 0x72, 0x64, 0x22, 0x50, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67,
	0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x2a, 0x6c, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x45, 0x41, 0x44, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x57,
	0x52, 0x49, 0x54, 0x45, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x49, 0x45, 0x57, 0x10, 0x03,
	0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x53, 0x45, 0x52, 0x4f, 0x4c, 0x45, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x50, 0x50, 0x4c,
	0x59, 0x52, 0x4f, 0x4c, 0x45, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x56, 0x4f, 0x55, 0x43, 0x48,
	0x46, 0x4f, 0x52, 0x10, 0x07, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x70, 0x65, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2d, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_meta_proto_rawDescOnce sync.Once
	file_meta_proto_rawDescData []byte
)

func file_meta_proto_rawDescGZIP() []byte {
	file_meta_proto_rawDescOnce.Do(func() {
		file_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_proto_rawDesc), len(file_meta_proto_rawDesc)))
	})
	return file_meta_proto_rawDescData
}

var file_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_meta_proto_goTypes = []any{
	(Operation)(0),            // 0: metadata.Operation
	(*ACE)(nil),               // 1: metadata.ACE
	(*ACL)(nil),               // 2: metadata.ACL
	(*AppliedRole)(nil),       // 3: metadata.AppliedRole
	(*UserAnnotation)(nil),    // 4: metadata.UserAnnotation
	(*AnnotationWrapper)(nil), // 5: metadata.AnnotationWrapper
	(*ACEPersist)(nil),        // 6: metadata.ACE_persist
	(*ACLPersist)(nil),        // 7: metadata.ACL_persist
	(*RolePersist)(nil),       // 8: metadata.Role_persist
	(*JsonPersist)(nil),       // 9: metadata.Json_persist
	(*TaggedString)(nil),      // 10: metadata.TaggedString
	(*S3Urls)(nil),            // 11: metadata.S3Urls
	(*SigningKey)(nil),        // 12: metadata.SigningKey
	(*anypb.Any)(nil),         // 13: google.protobuf.Any
}
var file_meta_proto_depIdxs = []int32{
	0,  // 0: metadata.ACE.op:type_name -> metadata.Operation
	2,  // 1: metadata.ACE.acls:type_name -> metadata.ACL
	13, // 2: metadata.AnnotationWrapper.Raw:type_name -> google.protobuf.Any
	0,  // 3: metadata.ACE_persist.op:type_name -> metadata.Operation
	7,  // 4: metadata.ACE_persist.acls:type_name -> metadata.ACL_persist
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_meta_proto_init() }
func file_meta_proto_init() {
	if File_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_proto_rawDesc), len(file_meta_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_proto_goTypes,
		DependencyIndexes: file_meta_proto_depIdxs,
		EnumInfos:         file_meta_proto_enumTypes,
		MessageInfos:      file_meta_proto_msgTypes,
	}.Build()
	File_meta_proto = out.File
	file_meta_proto_goTypes = nil
	file_meta_proto_depIdxs = nil
}
